package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class rule_set_define implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("id")
	private java.lang.String id;

	@org.kie.api.definition.type.Label("name")
	private java.lang.String name;

	@org.kie.api.definition.type.Label("defail")
	private java.lang.String defail;

	@org.kie.api.definition.type.Label(value = "test")
	private java.lang.String test;

	public rule_set_define() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getDefail() {
		return this.defail;
	}

	public void setDefail(java.lang.String defail) {
		this.defail = defail;
	}

	public java.lang.String getTest() {
		return this.test;
	}

	public void setTest(java.lang.String test) {
		this.test = test;
	}

	public rule_set_define(java.lang.String id, java.lang.String name,
			java.lang.String defail, java.lang.String test) {
		this.id = id;
		this.name = name;
		this.defail = defail;
		this.test = test;
	}

}