package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class test2 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "id")
	private java.lang.String id;

	public test2() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public test2(java.lang.String id) {
		this.id = id;
	}

}